# Generated by Django 5.2 on 2025-06-10 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0002_badge_icon_url_alter_badge_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='friends',
            field=models.ManyToManyField(blank=True, to='quests.userprofile'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
