# Generated by Django 5.2 on 2025-06-11 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0006_remove_userprofile_friends_remove_userprofile_level_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='happy_clients',
            new_name='competitions_participated',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='photo_captures',
            new_name='competitions_won',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='projects_completed',
            new_name='xp_collected',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='telephonic_talks',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='quests_completed',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
