# Generated by Django 5.2 on 2025-06-11 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0007_rename_happy_clients_userprofile_competitions_participated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='xp',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
