# Generated by Django 5.2 on 2025-06-11 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0008_userprofile_xp'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.TextField(blank=True),
        ),
    ]
