# Generated by Django 5.2 on 2025-06-11 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0009_userprofile_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='competition',
            old_name='end_date',
            new_name='end_datetime',
        ),
        migrations.RenameField(
            model_name='competition',
            old_name='start_date',
            new_name='start_datetime',
        ),
        migrations.AlterField(
            model_name='competition',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
