# Generated by Django 5.2 on 2025-06-11 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0010_rename_end_date_competition_end_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='level',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
